### PR TITLE
Fixes #3459

### PR DESCRIPTION
**Pull request by MaheshPulle7**
# Pull Request Review

## Checklist

- [x] Issue: https://github.ibm.com/TNC/tnc-o-tracking/issues/3459
- [x] List of related PRs. : None
- [x] Project builds without any errors.
- [x] Unit Tests updated (or created where needed) and all pass.
- [x] You have ran manual functional "smoke" test (does product as a whole still work?).
- [x] User Story meets the acceptance criteria - and passes. acceptance criteria should be understood at outset.
- [x] There is a PR for update of internal documentation for the affected Project(s) - README etc.
- [x]  **Description of the changes**: https://github.ibm.com/TNC/tnc-o-tracking/issues/3459

### CODE REVIEW

**Comment by MaheshPulle7** [comment]
Test Results:
[success.zip](https://github.com/IBM/sol003-lifecycle-driver/files/8207183/success.zip)

**Comment by MaheshPulle7** [comment]
Added NotificationLink.java file based on 2.5.1 spec ,as it structure not defined   in 3.5.1 spec

**Comment by lokanalla** [comment]
Hi @hhellyer , @owen-lynch-ibm , Could you please review this PR.

**Comment by MaheshPulle7** [comment]
Changes are done in script files as per 3.5.1 version

**Review by hhellyer — COMMENTED** [review]
With these changes is the driver still backwards compatible with SOL003 2.4.1 after this is merged? Looking at it I'm not sure if it is but I can't see from the attached planning items whether it is expected to still support 2.4.1 as well as 3.5.1.

Should both versions be supported now? If so is the code here backwards compatible with 2.4.1?

**Comment by MaheshPulle7** [comment]
@hhellyer The driver cannot be backward compatible for 2.4.1. To make it compatible the driver will need to be built and installed separately after doing few changes in code.

**Comment by lokanalla** [comment]
Hi, 
@hhellyer @owen-lynch-ibm , Could you please review this PR as we need to release the driver for EKS. 
Thanks,
Loka

**Review by hhellyer — APPROVED** [review]
Approving on the assumption that no longer supporting the old version is as intended by the original requirement.

**Review by owen-lynch-ibm — APPROVED** [review]

**Pull request merged**
